# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-added-large-files
      - id: debug-statements
        exclude: "^(.buildozer/|python-for-android/)"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.0
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
          - --explicit-package-bases
        exclude: "^(.buildozer/|python-for-android/)"

  # - repo: https://github.com/prettier/prettier
  #   rev: "2.8.0"
  #   hooks:
  #     - id: prettier
  #       files: \.(json|yml|yaml)$
  #       exclude: "^(.buildozer/|python-for-android/)"

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black]
        exclude: "^(.buildozer/|python-for-android/)"

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
        exclude: "^(.buildozer/|python-for-android/)"

  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.0.0
  #   hooks:
  #     - id: flake8
  #       args: [--max-line-length=88]
  #       exclude: "^(.buildozer/|python-for-android/)"

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        exclude: "^(.buildozer/|python-for-android/)"

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        exclude: "^(.buildozer/|python-for-android/)"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: "^(.buildozer/|python-for-android/)"

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.9
    hooks:
      - id: vulture
        args:
          - --min-confidence=80
          - --exclude=.buildozer/
          - --exclude=python-for-android/
        files: kivy_android_shopping/.*

  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.0
    hooks:
      - id: pylint
        exclude: "^(.buildozer/|python-for-android/)"

  # - repo: https://github.com/myint/docformatter
  #   rev: v1.6.0
  #   hooks:
  #     - id: docformatter
  #       args: ["--in-place", "--wrap-summaries=88", "--wrap-descriptions=88"]
  #       exclude: "^(.buildozer/|python-for-android/)"
